### PR TITLE
add fake profile images

### PR DESCRIPTION
**Pull request by eladeyal-intel**
from https://randomuser.me

image

image

### CODE REVIEW

**Comment by erdgeist** [comment]
I don't think it's a good idea to randomly add links to external services to tests. Can't we just provide some demo images locally and link to them?

**Comment by eladeyal-intel** [comment]
@erdgeist thanks for taking the time to review this.

It's not a "random service" - it's a service which is explictly set up for this pupose. The faces FAQ is explicitly permissive to use these faces for "Mock ups", which is what the data is used for. 

I looked at what "Faker" is doing - they also link to external services, they're not keeping images in their repository.

Note that the images are copied upon running `rails frab:add_fake_data`, so after that the images are safe within the test db.

I added a begin-rescue block so in the event this site becomes unavailable/down, the fake users are created sans photo.

**Comment by eladeyal-intel** [comment]
@erdgeist i can try https://github.com/guinslym/Uifaces instead. Do you think it's better?

**Comment by ScottyTM** [comment]
> @erdgeist i can try https://github.com/guinslym/Uifaces instead. Do you think it's better?

http://uifaces.com seems to no longer exist.

**Comment by eladeyal-intel** [comment]
plus! It does not really affect tests, since the `add_fake_data` is never used as part of the test suite.

**Pull request closed without merging**
