### PR TITLE
cfp/people: show event date and room in overview table

### PR DESCRIPTION
**Pull request by zonque**
This way, speakers can see where they are scheduled at and when.

### CODE REVIEW

**Comment by zonque** [comment]
Rebased to trigger the tests

**Comment by zonque** [comment]
To give some more background: We've had the situation that speakers would need to search for themselves in the public schedule once it's published, or come up at the information desk to ask for that. This patch helped a lot.

**Comment by manno** [comment]
I'm hesitant because some conference might not want speakers to now directly. It's a secret if the talk has been accepted until the confirmation mails are sent: https://github.com/frab/frab/blob/master/app/views/cfp/people/_table.html.haml#L17
Location and time are communicated by coordinators via mail, because they might change a lot until the public schedule is finalized.

I agree it would be great to have it in the interface, but we should gate it by checking `conference.event_state_visible`.

**Comment by zonque** [comment]
Good point! Will change accordingly.

**Comment by manno** [comment]
fixed indentation and merged

**Pull request closed without merging**
