### PR TITLE
Add kqueue support for BSD systems

### PR DESCRIPTION
**Pull request by erdgeist**
I do not know if the require 'rbconfig' in Gemfile is correct, but rails keeps nagging me to use kqueue under *bsd and I whole-heartedly agree that polling on BSDs is insane.

### CODE REVIEW

**Comment by manno** [comment]
I have no idea how to test the consequences of this change. I guess it's harmless?

**Comment by erdgeist** [comment]
This is what I usually am educated by, when starting the rails app:

```
=> Rails 5.1.2 application starting in development on http://192.168.216.129:3000
=> Run `rails server -h` for more startup options
  Please add the following to your Gemfile to avoid polling for changes:
    require 'rbconfig'
    if RbConfig::CONFIG['target_os'] =~ /(?i-mx:bsd|dragonfly)/
      gem 'rb-kqueue', '>= 0.2'
    end
```
And that's what I did. On BSD, the app does work with (no nagging message) and without this patch and I don't have a way to measure the performance impact. Yet, I understand what they mean, kqueue is the default kernel event signalling mechanism in BSDs and whenever I implement anything tcp related with kqueue.

**Comment by manno** [comment]
Sadly this leads to a modified `Gemfile.lock` on Linux.

I tried an alternative approach in the bsd-kqueue branch, does this work for you?

**Comment by erdgeist** [comment]
LGTM. Vielen Dank.

**Pull request closed without merging**
