### PR TITLE
Use i18n-tasks to fix and normalize translations

### PR DESCRIPTION
**Pull request by neomilium**
In order to automatically process translations files (normalize, missing, unused, etc.), this PR adds a dependency on `i18n-tasks` gem.

https://glebm.github.io/i18n-tasks/

Few conflicts have been detected by `i18n-tasks` and have been manually fixed.

Please note that rspec test is provided but not used (no rspec addition in Gemfile).

### CODE REVIEW

**Comment by neomilium** [comment]
@erdgeist You've been interested in [translation refactoring](https://github.com/frab/frab/pull/376#issuecomment-349691113). Can you please comment on this PR?

I have a bunch of local changes that I like to propose on top of it to improve translation.

Thanks

**Comment by neomilium** [comment]
Some details about commits that could help to merge it:
* The first only add `i18n-tasks` to `Gemfile`, resulting an addition of `i18n-tasks` and dependencies to `Gemfile.lock`;
* The second removes duplicates detected by `i18n-tasks`;
* The last one is the result of running `bundle exec i18n-tasks normalize -p`, without any other modifications, which merge translations files into one per language as expected by @mtancoigne in closed PR #382.

IMHO, using `i18n-tasks` will be helpful to ease translation and translation improvements as expected in issue #185.

For example, running `bundle exec i18n-tasks missing de` detects 737 missing translations in DE.

@manno How can I help more to ease this PR merge ?

**Comment by manno** [comment]
Merged via 66717065078e46bb7c92dd316f0d34138e937e42

I replaced the rspec script with minitest, I hope that works for you.

**Comment by neomilium** [comment]
Thanks, its now possible to push more fixes from our internal branch, great !

**Pull request closed without merging**
