### PR TITLE
add : Dokku deployment environment + instructions

### PR DESCRIPTION
**Pull request by almereyda**
#### Hypothesis

> This implements small and basic changes to deploy frab with Dokku.

#### Tests

* [x] frab understands `DATABASE_URL` from ENV
We don't want to commit any configuration to the git tree. *Double check*
* [ ] dokku deployment instructions contain note about mandatory SSL
self-signed is sufficient and localhost is not forbidden by the policy

### CODE REVIEW

**Comment by almereyda** [comment]
We may want to to implement the `DATABASE_URL` environment variable for database connections before merging this.

**Comment by almereyda** [comment]
Also there is currently still a problem with the migrations after setting up the database and running:

```
dokku run frab bundle exec rake db:migrate
```

---

```
== 20110930110209 RemoveDeviseSpecificColumnsFromUsers: migrating =============
-- rename_column(:users, :encrypted_password, :password_digest)
   -> 0.0047s
-- remove_column(:users, :password_salt)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedColumn: ERROR:  column "password_salt" of relation "users" does not exist
: ALTER TABLE "users" DROP "password_salt"/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:415:in `remove_column'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:662:in `block in method_missing'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `block in say_with_time'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `say_with_time'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:651:in `method_missing'
/app/db/migrate/20110930110209_remove_devise_specific_columns_from_users.rb:5:in `change'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'                                                                                                                                    [64/1747]
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
ActiveRecord::StatementInvalid: PG::UndefinedColumn: ERROR:  column "password_salt" of relation "users" does not exist
: ALTER TABLE "users" DROP "password_salt"
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:415:in `remove_column'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:662:in `block in method_missing'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `block in say_with_time'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `say_with_time'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:651:in `method_missing'
/app/db/migrate/20110930110209_remove_devise_specific_columns_from_users.rb:5:in `change'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
PG::UndefinedColumn: ERROR:  column "password_salt" of relation "users" does not exist
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/app/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/schema_statements.rb:415:in `remove_column'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:662:in `block in method_missing'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `block in say_with_time'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:631:in `say_with_time'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:651:in `method_missing'
/app/db/migrate/20110930110209_remove_devise_specific_columns_from_users.rb:5:in `change'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:605:in `exec_migration'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:589:in `block (2 levels) in migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:588:in `block in migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:587:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:765:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'                                                                                       [0/1747]
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/transactions.rb:220:in `transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:1041:in `ddl_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:956:in `block in migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `each'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:952:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:820:in `up'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/migration.rb:798:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/app/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.4/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

---

This needs to finish successfully to be able to

```
dokku run frab bundle exec rake db:seed
```

**Comment by almereyda** [comment]
According to https://github.com/fossasia/open-event/issues/17 @rafalkowalski managed to deploy Frab on Heroku. I wonder how, as #160 never got merged.

**Comment by almereyda** [comment]
`dokku frab bundle exec rake db:setup` works, despite the task cannot create the database.
Yet, logging in is not possible.

**Comment by manno** [comment]
Hi, for new deployments run rake db:setup. I guess db:create fails because you dokku db user is missing some permissions. More installation instructions can be found in the README.md as well as in bin/setup.

To use dotenv (.env.production) and DATABASE_URL in config/database.yml you might want to implement something similar to http://stackoverflow.com/questions/28953923/not-reading-env-variables-in-database-yml-rails-4-2-0-rubymine-7-postgres-ru

**Comment by rafalkowalski** [comment]
Hi, If you need my help I can help you :)

**Comment by almereyda** [comment]
Hi @manno and @rafalkowalski,

from the instance running at http://frap.apps.ecobytes.net I'm now hunting down a CSRF error. From `log/production.log` after `dokku enter frab`:

```
W, [2015-10-14T18:30:06.736662 #9]  WARN -- : Can't verify CSRF token authenticity
```

Therefore the admin user login works (I am receiving errors if I use the wrong password), but something else still fails. Will keep you posted. And trying to keep this PR with less than #160 ;)

**Comment by almereyda** [comment]
@manno @rafalkowalski Could you please review the updated PR description for any missing criteria before this PR could be merged?

In the end I remembered something about SSL and CSRFs. Especially as the term `authenticity` had been used in the `WARN` message above. Creating a self-signed certificate was for now sufficient.

We avoid the use of dotenv as commiting configuration into the git tree is not an option.

**Comment by manno** [comment]
According to http://guides.rubyonrails.org/v4.2.5/configuring.html#configuring-a-database the `DATABASE_URL` environment variable will take precedence over an existing `database.yml`.
If this works section 2 of your install instructions could be omitted.

I just wanted to add, that you don't have to commit your dotenv files to git. If you are using capistrano you could just symlink them from the shared folder and use some other mechanism to distribute them to your servers. But there is no need to use a dotenv file in production, especially since dokku already has a mechanism to put variables into the environment.

**Comment by almereyda** [comment]
Yes, `DATABASE_URL` is confirmed to work out-of-the-box. Let me revisit this PR then and ask for merge once ready.

**Comment by almereyda** [comment]
@manno @rafalkowalski It is believed the latest commits allow for merging with `upstream/master`.

**Pull request merged**
