### PR TITLE
Add more reports for events

### PR DESCRIPTION
**Pull request by zonque**
Add report for events without abstract.

### CODE REVIEW

**Comment by zonque** [comment]
Rebased and updated this one with more collected details.

**Comment by zonque** [comment]
Ah, nice. So now that master has moved forward without considering open PRs, almost all of my pending branches cannot be merged anymore. Also, I haven't got feedback about whether the new features are wanted at all. Until that happens, I won't rebase any of my code.

**Comment by sebix** [comment]
Looking forward to see the `events_without_abstract` report in frab :)

Are you sure, that ` app/models/event.rb` isn't missing a scope for this report?

**Comment by zonque** [comment]
@sebix not sure what you mean. The PR adds a new scope `with_more_than_one_speaker` to `Event`. Doesn't the code work for you? It does for me.

**Comment by sebix** [comment]
Ah, now I saw that the logic for the query is directly implemented in the controller, not in the model.

**Comment by zonque** [comment]
@sebix yes, the 2nd one is an special case that is open-coded in the controller. It follows the example of other such report specific queries.

**Comment by manno** [comment]
@zonque sorry about the open pull requests. I'll try to give you feedback as soon as possible, like this weekend?

**Comment by zonque** [comment]
Sure, I'm not actively working on frab right now, so I'm in no hurry.

**Comment by zonque** [comment]
Now rebased against current master.

**Comment by manno** [comment]
Merged, too. Thanks again :+1:

**Pull request closed without merging**
