### PR TITLE
Third party authentication

### PR DESCRIPTION
**Pull request by eladeyal-intel**
See #499

### CODE REVIEW

**Comment by manno** [comment]
Hey this is great, a lot of people were asking for that.

I didn't have time to test it and I'm worrying about how easy it is to support this, e.g. when updating to Rails 6. It looks like this is no problem, what is your impression of the Gems, are they in widespread use and updated regulary?

**Comment by eladeyal-intel** [comment]
I'm sorry I have no idea. This is more or less my first venture into Ruby & Rails. My work was mostly cut and paste from the how-to, most stuff went smoothly. If one specific strategy gem is not good, adding a different one is easy - take a look at the Google commit.

**Comment by manno** [comment]
Omniauth Gems seem to be very popular (Sinatra, etc). 

I think https://github.com/cschiewek/devise_ldap_authenticatable has the advantage that we could also access the users ldap data. That would be nice to keep roles in a central place to share them with other systems.
However it also looks more complicated. I merging this now from the command line, because I commented `env.example` and rebased against master.

**Comment by manno** [comment]
Merged in 1f219763

**Pull request closed without merging**
