### PR TITLE
Add mass mail feature

### PR DESCRIPTION
**Pull request by zonque**
This pull request implements a simple mass mail feature that we used during a conference to contact confirmed speakers with latest updates. The filter mechanism that controls the list of receivers is easily extendable. It also includes a simple template engine that allows a bit of mail content personification.

### CODE REVIEW

**Comment by sebix** [comment]
As I don't see anything referring to SMTP, how are mails sent? Directly or via the local mailer, e.g. `mail` or `sendmail`?

**Comment by zonque** [comment]
That is up to the Rails environments settings and is configured once for all occasions in which mail is sent.

This PR also adds `letter_opener`, a gem that opens mail in the default web browser instead of sending it to a mail server, when the server is running in `development` environment.

**Comment by sebix** [comment]
Would be nice if the configuration would be documented somewhere.

**Comment by zonque** [comment]
Rebased and slightly refactored again. Also added a commit for unit testing.

**Comment by manno** [comment]
This is great. Is database cleaner really a speed improvement for our test suite?

**Comment by zonque** [comment]
So, what's the way forward in this case? Why did you cherry-pick only one out of three commits, and how would you proceed with the other two?

**Comment by manno** [comment]
The commit was easy to pick and I wanted to add database_cleaner. The other two need rebasing, that's why I added the 'scheduled' tag. It's kind of scheduled for merging.

**Comment by zonque** [comment]
I rebased this branch against origin/master now. Seems to work just fine. Feedback appreciated :)

**Comment by manno** [comment]
Merged too

**Pull request closed without merging**
