### PR TITLE
fix filter by blank string

### PR DESCRIPTION
**Pull request by eladeyal-intel**
This PR fixes a bug from #579.

To reproduce the bug: Create two events. 1 with track field empty and 1 with track field populated. Open All Events. Click the filter item next to Track. Check V next to "(blank)", hit OK. It will not filter correctly.

So this fixes it.

### CODE REVIEW

**Comment by eladeyal-intel** [comment]
@erdgeist would you like to review this?

**Comment by eladeyal-intel** [comment]
@manno would you like to review this?

**Comment by eladeyal-intel** [comment]
@manno

**Comment by eladeyal-intel** [comment]
@erdgeist ?

**Review by saerdnaer — APPROVED** [review]

**Pull request merged**
