### PR TITLE
Expenses

### PR DESCRIPTION
**Pull request by zonque**
Add a data model to store expenses for people of a conference.

This PR adds a new model, its views, and a report to show which non-reimbursed expenses for a conference exist.

### CODE REVIEW

**Comment by zonque** [comment]
Pushed a rebased version that also contains a simple unit test.

**Comment by manno** [comment]
The conferences I know explicitly decided against such a field in the past, since reimbursements are not very common.

**Comment by sebix** [comment]
We also don't do it because then many people would request a reimbursement without needing it and straining the budget. Those who really need it, ask via mail or direct contact.

If this feature can be deactivated without changes in the code, I'm not against it (can't interpret the code if this is the case).

**Comment by zonque** [comment]
> The conferences I know explicitly decided against such a field in the past, since reimbursements are not very common.

Well, and we decided for it, for valid reasons. For our conference, we need a way to keep track about expenses we eventually need to reimburse to speakers, hence I added this feature. If you're concerned about people adding unjustified expenses themselves, this can be made a conference organizer feature only (not sure how I implemented it back then).

In general, all the PRs I opened add features that are crucial for us in order to run our conference. Things that don't find their way upstream will need rebasing on our side, which is extra work I'd like to avoid.

**Comment by manno** [comment]
As far as I can see this does not add any fields to the CfP views. Introducing this for conference organizers only sound good.

**Comment by zonque** [comment]
Ok, will have a look at what's left of these PRs once the dust settles and I find some time to continue working on all that. It might take weeks or months though.

**Comment by zonque** [comment]
I just rebased this branch against current master and refactored all necessary bits to Rails4, dotenv, SimpleForm etc.

As mentioned earlier, this does not contain a CfP form addition, so it's considered a feature for administrators only.

Works fine in my tests. Please have a look!

**Comment by manno** [comment]
Thanks, I merged the feature. I put the schema.rb changes in a separate commit to avoid merge conflicts. I'm not sure if reviewers should be able to view expenses, but we can deal with that later.

**Comment by zonque** [comment]
Yes, the role model is questionable. It should probably be dealt with in a separate PR or so.

**Pull request closed without merging**
